### ISSUE TITLE
Logger does not respect the "Enable logging" setting

### ISSUE THREAD

**Issue by lakrisgubben** [SwedbankPay/swedbank-pay-woocommerce-core#16]
The `log` method on the `WC_Adapter` class does not respect the "Enable logging" setting for the current payment gateway and instead always writes to the log. An easy fix for this is to add the following as the first lines in the `log` method.

```PHP
if (!$this->getConfiguration()[ConfigurationInterface::DEBUG]) {
    return;
}
```

Happy to make a PR for this, but maybe y'all have a better solution for it. :)

**Comment by lakrisgubben** [comment]
Any updates on this and https://github.com/SwedbankPay/swedbank-pay-woocommerce-payments/issues/46 @asbjornu @aait? :)

**Comment by aait** [comment]
@lakrisgubben See this line https://github.com/SwedbankPay/swedbank-pay-woocommerce-core/blob/master/src/SwedbankPay/Core/Core.php#L171
```
        if (!$this->configuration->getDebug()) {
            return;
        }
```
This line does the same behavior

**Comment by lakrisgubben** [comment]
thanks for the reply @aait! We still get our logs filled with messages even though I've disabled logging, so something is up here. Looked some more at the logs and it seems like all of the messages are about either "Incoming callback" or the "Background queue". So maybe this issue can be closed, but this one needs investigation? https://github.com/SwedbankPay/swedbank-pay-woocommerce-payments/issues/46

**Comment by lakrisgubben** [comment]
@aait the issue is that `WC_Gateway_Swedbank_Pay_Cc::return_handler` calls `WC_Adapter::log`, not `Core::log`. And since `Core::log` is a private function it can't be called from `WC_Gateway_Swedbank_Pay_Cc::return_handler`. So either `Core::log` needs to be exposed and then changes made in `WC_Gateway_Swedbank_Pay_Cc` or `WC_Adapter::log` needs to have the same logic as `Core::log`.

**Comment by aait** [comment]
https://github.com/SwedbankPay/swedbank-pay-woocommerce-core/commit/a026c4f6270f307660461755118521f445ffbf0c
https://github.com/SwedbankPay/swedbank-pay-woocommerce-core/commit/97cd3555a310462cdbef293904191eb007bace88
