### ISSUE TITLE
Issue when part refunding an order.

### ISSUE THREAD

**Issue by noahsvensson** [SwedbankPay/swedbank-pay-woocommerce-core#24]
We have an issue where we try to partly refund an order. Everything is correct in Swedbank Pay and Woocommerce initially the problem is after the transaction is saved. You check for a param called `remainingReversalAmount` that doesn't exist in the response yet. https://github.com/SwedbankPay/swedbank-pay-woocommerce-core/blob/97cd3555a310462cdbef293904191eb007bace88/src/SwedbankPay/Core/Library/OrderAction.php#L328 This line is the one that's causing problems. You are casting an undefined parameter to an int which will result in 0 causing the condition to be true. This will mark the order as "Refunded" which automatically creates a refund for the rest of the order value (in Woocomerce not in Swedbank Pay). Everything is correct in Swedbank Pay but this impacts the statistics in Woocomerce. 

The solution that I've found is that you ignore this step here and listen to the webhook instead. But maybe you guys have a better solution. 

Let me know if you need more information!

Regards Noah

**Comment by asbjornu** [comment]
Thanks for the report, @noaholsson! We'll have a look into this ASAP. Pull requests are also welcome.
