### ISSUE TITLE
Calls to updateOrderStatus() pass transaction number instead of id

### ISSUE THREAD

**Issue by joiglifberg** [SwedbankPay/swedbank-pay-woocommerce-core#27]
All calls in [OrderAction.php](https://github.com/SwedbankPay/swedbank-pay-woocommerce-core/blob/master/src/SwedbankPay/Core/Library/OrderAction.php) to `updateOrderStatus()` incorrectly pass the transaction number instead of the transaction id as the last argument.

Example link:
https://github.com/SwedbankPay/swedbank-pay-woocommerce-core/blob/master/src/SwedbankPay/Core/Library/OrderAction.php#L703

**Comment by aait** [comment]
@joiglifberg That is not bug. That is expectable construction. May be there's wrong varibale name: `transction number` instead of `transaction_id`
