### ISSUE TITLE
fetchTransactionsAndUpdateOrder() in OrderAction.php depends heavily on the WooCommerce plugin

### ISSUE THREAD

**Issue by joiglifberg** [SwedbankPay/swedbank-pay-woocommerce-core#28]
Method [fetchTransactionsAndUpdateOrder()](https://github.com/SwedbankPay/swedbank-pay-woocommerce-core/blob/b676c6ccd5affb87fdd198e5bee16ff474e0cf5c/src/SwedbankPay/Core/Library/OrderAction.php#L514) in [OrderAction.php](https://github.com/SwedbankPay/swedbank-pay-woocommerce-core/blob/master/src/SwedbankPay/Core/Library/OrderAction.php) is dependent on the [Swedbank Pay WooCommerce Payments plugin](https://github.com/SwedbankPay/swedbank-pay-woocommerce-payments) due to the call to `$this->saveTransactions()` which in the end is trying to call `$this->gateway->transactions->import($transaction_data, $order_id);` in [WC_Swedbank_Pay_Transactions](https://github.com/SwedbankPay/swedbank-pay-woocommerce-payments/blob/master/includes/class-wc-swedbank-pay-transactions.php) which is located in the above mentioned plugin.

I feel like this library should be able to run independently from the plugin, or is this not the case?

**Comment by joiglifberg** [comment]
The same thing applies to calls to the [saveTransaction()](https://github.com/SwedbankPay/swedbank-pay-woocommerce-core/blob/master/src/SwedbankPay/Core/Library/TransactionAction.php#L15) method.

**Comment by aait** [comment]
@joiglifberg  This library can be used independently the plugin. It assumes creation of custom `PaymentAdapter` where developer implementes such methods like `saveTransaction`. There's can be any method of transaction saving. For example, WooCommerce adapter uses `WC_Swedbank_Pay_Transactions`. I can 't say that `fetchTransactionsAndUpdateOrder` and `saveTransaction()` methods heavily depend on the WooCommerce plugin.

**Comment by joiglifberg** [comment]
Youre right, I did not think of that, thanks!
