### ISSUE TITLE
Card payments not working after PR #54

### ISSUE THREAD

**Issue by lakrisgubben** [SwedbankPay/swedbank-pay-woocommerce-core#56]
Hey,

the changes to the WC_Adapter class in #54 have had the unfortunate consequence of breaking card payments for us (I haven't deployed it to production yet so no worries. :) ), we use the[ Swedbank Pay WooCommerce Payments plugin](https://github.com/SwedbankPay/swedbank-pay-woocommerce-payments). The problematic change are these lines https://github.com/SwedbankPay/swedbank-pay-woocommerce-core/pull/54/files#diff-89a77008217563f17d3a6fe6a0152dda195c02c398465b7c5d879a94144ab877R148-R159.

The issue here is the boolean check `$this->gateway->reject_credit_cards` (and you can replace `reject_credit_cards` with any of [the other properties](https://github.com/SwedbankPay/swedbank-pay-woocommerce-core/pull/54/files#diff-89a77008217563f17d3a6fe6a0152dda195c02c398465b7c5d879a94144ab877R148-R159)) which will always be true since [the value of](https://github.com/SwedbankPay/swedbank-pay-woocommerce-payments/blob/682567a796bc0c5afb53a691266b89bbb775c55b/includes/class-wc-gateway-swedbank-pay-cc.php#L117) `reject_credit_cards` is either `(string) 'yes'` or `(string) 'no'`. So no matter what one has choosen for these options they will always be set to true when posting to the swedbank pay api which means that the card payment will fail in swedbank pay with the error `ACCOUNTHOLDERTYPEREJECTED` or `CARDTYPEREJECTED`. Of course I don't know the reasoning behind this change, or if it's just for us it breaks, but reverting these lines (or changing them to use the [same logic as the save_cc property](https://github.com/SwedbankPay/swedbank-pay-woocommerce-core/pull/54/files#diff-89a77008217563f17d3a6fe6a0152dda195c02c398465b7c5d879a94144ab877R142-R143)) makes the card payments work again.

**Comment by aait** [comment]
@lakrisgubben Thank you! We will fix it

**Comment by aait** [comment]
@lakrisgubben It has been fixed in the Wordpress Plugins directory https://profiles.wordpress.org/swedbankpay/#content-plugins.
We will merge the fix after review there

**Comment by lakrisgubben** [comment]
Thanks for the quick response @aait! :)

It looks like `ConfigurationInterface::USE_PAYER_INFO` is declared twice now in https://github.com/SwedbankPay/swedbank-pay-woocommerce-core/commit/ded00f763e1a5d7d8300332854b1636734779661

I use the plugin from github so I'll test this out once #57 is merged and a 4.0.1 is released in this repo.

best
