### ISSUE TITLE
Enhance hooks for modifying posted data

### ISSUE THREAD

**Issue by marteinn** [SwedbankPay/swedbank-pay-woocommerce-core#59]
Hi! 👋 

This issue is a follow up to https://github.com/SwedbankPay/swedbank-pay-woocommerce-core/issues/40 and contains feedback on the hooks introduced in https://github.com/SwedbankPay/swedbank-pay-woocommerce-core/pull/54/commits

Background: In my current Swedbank Pay implementation I need to pass along data in a certain way to get the Swedbank Pay reports output data correctly, those requirements are:
- `subsite`: We use subsite to separate oders by type (Membership or donation). This will get us different report files
- `payeeReference`: We use our own payeeReference to supply the Swedbank Pay report with a order id coming from a CRM, we do this to get the CRM Order ID showing in our reports. In best of worlds `orderReference` should be used here (as `payeeReference` should be unique per request) but the report are currently not built like that. I have raised the issue with Swedbank Pay support so I think its on the readmap.
- `productCategory`: If something is a membership or gift

Looking at the new filters and comparing them with my requirements, here are some feedback:

- `swedbank_pay_subsite`
In my use case we set subsite according to order and it's containing product taxonomy, but it seems like the filter provided does not supply the order id (like `swedbank_pay_order_reference` does). So this filter does not cover my use case.

- `payeeReference`
No filter for this field and there are no filter for me to add it before posting data to gateway.

- `productCategory`
No filter for this field and there are no filter for me to add it before posting data to gateway.

I think much of this could be solved by either passing along order ID with the filter or introducing a more general pre request hook where data can be modified directly.

**Comment by aait** [comment]
Hi @marteinn 
Why can't you do it like that:
> `subsite`: We use subsite to separate oders by type (Membership or donation). This will get us different report files
> In my use case we set subsite according to order and it's containing product taxonomy, but it seems like the filter provided does not supply the order id (like swedbank_pay_order_reference does). So this filter does not cover my use case.

```php
add_filter( 'swedbank_pay_subsite', 'swedbank_pay_subsite', 2, 10 );
function swedbank_pay_subsite($subsite, $payment_id) {
	$order_id = absint( WC()->session->get( 'order_awaiting_payment' ) );
	if ($order_id > 100) {
		return 'custom_subsite';
	}

	return $subsite;
}
```

> `payeeReference`
> No filter for this field and there are no filter for me to add it before posting data to gateway.
```php
add_filter( 'swedbank_pay_payee_reference', 'swedbank_pay_payee_reference', 2, 10 );
function swedbank_pay_payee_reference($reference, $order_id) {
	return $reference . $order_id;
}
```

Or use like that:

> `productCategory`
> No filter for this field and there are no filter for me to add it before posting data to gateway.
```php
add_filter( 'swedbank_pay_payment_object', 'swedbank_pay_payment_object', 2, 10 );
function swedbank_pay_payment_object($object, $order_id) {
	$payeeInfo->setProductCategory('Category1');
	$object->setPayeeInfo($payeeInfo);
	return $object;
}
```


You can use `swedbank_pay_payment_object`. It's very powerful hook which allow to modify any posted data

**Comment by marteinn** [comment]
Apologies for the late reply, actually `swedbank_pay_payment_object` seems to be a perfect fit for us, thanks for this!

I'm now trying to replace our current forked plugin with the most recent plugin + `swedbank_pay_payment_object`, will report back here in a couple of weeks after we have done some testing.

**Comment by marteinn** [comment]
Hi there! A follow up, I have done some testing and noticed that `swedbank_pay_payment_object` does not trigger on capture calls, can you confirm this? 

In our scenario we use Instant capture and need to detect "Capture" calls so we can override `payeeReference`. The reason is:
- `payeeReference` is used to represent "Order Id" in Swedbank Pay reports (we can't use order order reference field)
- `payeeReference` needs to be unique per request (so we can't pass it twice)
- Only the latest `payeeReference` will appear in the report (that is Capture, so we can't just pass it on Authorization)

This is an example of our current implementation:
```php
function filter_swedbank_pay_payment_object($object, $orderId) {
        $payment = $object->getPayment();
        $payeeInfo = $payment->getPayeeInfo();

        ...

        $intent = $payment->getIntent();

        if (in_array($intent, ['AutoCapture', 'Capture'])) {  // Never happens
            $payeeInfo->setPayeeReference($crmOrderNumber);
            $payment->setPayeeInfo($payeeInfo);
        }
```

Would it be possible to let the `swedbank_pay_payment_object` also apply to Capture calls happening in `SwedbankPay/Core/Library/OrderAction.php`? Or is there another way we can solve this?

Thanks!

**Comment by marteinn** [comment]
Just wanted to remind about this issue, thanks!

**Comment by marteinn** [comment]
Hi! Just wanted to send another reminder about this issue. Thanks!

**Comment by olegisk** [comment]
@marteinn Hi. I've implemented wp filter `swedbank_pay_transaction_object` which allow you to handle such requests like that. Please check https://github.com/SwedbankPay/swedbank-pay-woocommerce-core/pull/72

**Comment by marteinn** [comment]
@olegisk I took a brief look and it looks like it would solve our issue. Do you have a ETA to when this might be merged in core and available to https://github.com/SwedbankPay/swedbank-pay-woocommerce-payments? Thanks!

**Comment by olegisk** [comment]
@marteinn It's already there

**Comment by marteinn** [comment]
@olegisk Thanks for the help! It seems like I got it working now.

Two follow up questions:

1. Is there a reliable way to detect type of transaction, as I only want it to run on Capture/AutoCapture? `getOperation` is empty in the hook, so right now I do this to check if it is a capture.

```php
$transactionData = $transactionObject->getTransaction();
$transactionDataClass = get_class($transactionData);
$transactionDataClassByPath = explode("\\", $transactionDataClass);
$transactionType = end($transactionDataClassByPath);
$isCapture = $transactionType == "TransactionCapture";
```

Would love to have a cleaner solution here.

2. Will this code also work on AutoCapture calls?

My full hook below for reference:
```php
function filter_swedbank_pay_transaction_object($transactionObject, $orderId) {
    $transactionData = $transactionObject->getTransaction();

    $transactionDataClass = get_class($transactionData);
    $transactionDataClassByPath = explode("\\", $transactionDataClass);
    $transactionType = end($transactionDataClassByPath);
    $isCapture = $transactionType == "TransactionCapture";

    if ($isCapture) {
        $wcOrder = wc_get_order($orderId);
        $crmOrderNumber = $wcOrder->get_meta('crmOrderNumber');

        $transactionData->setPayeeReference($crmOrderNumber);
        $transactionObject->setTransaction($transactionData);
    }

    return $transactionObject;
}

**Comment by olegisk** [comment]
> 2. Will this code also work on AutoCapture calls?

What kind of AutoCapture calls do you mean?

> 1. Is there a reliable way to detect type of transaction, as I only want it to run on Capture/AutoCapture? getOperation is empty in the hook, so right now I do this to check if it is a capture.

Please provide us full code

**Comment by marteinn** [comment]
> What kind of AutoCapture calls do you mean?

I'm referring to the intent "AutoCapture" and are mostly thinking about it in conjunction with credit card transfers. You can find it in the settings for `payex_psp_cc` under "Auto Capture Intent".

> Please provide us full code

The code for detecting if it's a capture? It is actually embedded in my sample above, but here are the bits that builds up `$isCapture` for clarity.

```php
$transactionData = $transactionObject->getTransaction();
$transactionDataClass = get_class($transactionData);
$transactionDataClassByPath = explode("\\", $transactionDataClass);
$transactionType = end($transactionDataClassByPath);
$isCapture = $transactionType == "TransactionCapture";

echo "Is this a capture " . ($isCapture ? "YES" : "NO");
```

If there any other samples you are thinking of just let me know.

**Comment by marteinn** [comment]
Hi! Just wanted to send a reminder about this issue. Thanks!

**Comment by marteinn** [comment]
Hi! Just wanted to send another reminder about this issue. My main question is basically: "Is there a better way to detect if there is a capture within the `filter_swedbank_pay_transaction_object` hook? My method here is pretty brittle.

Thanks!

**Comment by olegisk** [comment]
@marteinn Thank you,
I think your code looks very well:
```php
function filter_swedbank_pay_transaction_object($transactionObject, $orderId) {
    $transactionData = $transactionObject->getTransaction();

    $transactionDataClass = get_class($transactionData);
    $transactionDataClassByPath = explode("\\", $transactionDataClass);
    $transactionType = end($transactionDataClassByPath);
    $isCapture = $transactionType == "TransactionCapture";

    if ($isCapture) {
        $wcOrder = wc_get_order($orderId);
        $crmOrderNumber = $wcOrder->get_meta('crmOrderNumber');

        $transactionData->setPayeeReference($crmOrderNumber);
        $transactionObject->setTransaction($transactionData);
    }

    return $transactionObject;
}
```
